version: '3.8'

services:
  truthshield-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./truthshield.db
      - ENVIRONMENT=demo
      - DEBUG=true
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-demo}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-demo}
    volumes:
      - ./demo_data:/app/demo_data
      - ./src:/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # Redis für Caching (optional, aber macht Demo professioneller)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: